export { default as Patients } from "./Patients";
export { default as CreatePatients } from "./CreatePatients";
export { default as ViewPatients } from "./ViewPatients";
export { default as SearchPatients } from "./SearchPatients";
export { default as CreatePatientRecord } from "./CreatePatientRecord";
export { default as CreateRecord } from "./CreateRecord";
export { default as PatientRecords } from "./PatientRecords";
export { default as ViewPatientRecord } from "./ViewPatientRecord";
export { default as PatientInfo } from "./PatientInfo";