export { default as Patients } from "./Patients";
export { default as CreatePatients } from "./CreatePatients";
export { default as ViewPatients } from "./ViewPatients";
export { default as SearchPatients } from "./SearchPatients";
export { default as CreatePatientRecord } from "./CreatePatientRecord";
export { default as CreateRecord } from "./CreateRecord";
export { default as PatientRecords } from "./PatientRecords";
export { default as ViewPatientRecord } from "./ViewPatientRecord";
export { default as PatientInfo } from "./PatientInfo";
export { default as SearchPatientRecord } from "./SearchPatientRecord";
export { default as SearchRecord } from "./SearchRecord";
export { default as SearchForm } from "./SearchForm";
export { default as DocForms } from "./DocForms";
export { default as CreateForms } from "./CreateForms";
export { default as ViewForms } from "./ViewForms";
export { default as FormResponse } from "./FormResponse";
export { default as CreateForm } from "./CreateForm"
export { default as FormsType } from "./FormsType"
export { default as ShowForm } from "./ShowForm";
export { default as FormFormat } from "./FormFormat";